### ISSUE TITLE
Can you help me how to add this plugin to tomcat distribution of camunda

### ISSUE THREAD

**Issue by TEJAPS** [StephenOTT/camunda-formio-plugin#34]
Can you help me how to add this plugin to tomcat distribution of camunda.

![image](https://user-images.githubusercontent.com/29141451/94046642-9578ff00-fdee-11ea-8fc6-f3fcf0c4101f.png)

![image](https://user-images.githubusercontent.com/29141451/94046670-a32e8480-fdee-11ea-9cf5-9cf8d7398d4d.png)

**Comment by StephenOTT** [comment]
Take a look here:

https://github.com/StephenOTT/camunda-formio-plugin#typical-camunda-deployment

https://github.com/StephenOTT/camunda-formio-plugin/blob/master/docker/Dockerfile

https://github.com/StephenOTT/camunda-formio-plugin/blob/master/docker/bpm-platform.xml#L38-L40

**Comment by TEJAPS** [comment]
Can you please provided any video reference as i am not to understand, how can i add this plugin to my tomcat camunda distribution.

**Comment by StephenOTT** [comment]
@TEJAPS  to install on a tomcat distribution you follow the same steps that are described in the dockerfile:

```
1. COPY ./tasklist/scripts/. /camunda/webapps/camunda/app/tasklist/scripts
2. COPY ./tasklist/styles/. /camunda/webapps/camunda/app/tasklist/styles
3. COPY ./forms/. /camunda/webapps/forms/

4. COPY ./formfieldvalidator-*-server-plugin.jar /camunda/lib/formfieldvalidator-server-plugin.jar

5. COPY ./bpm-platform.xml /camunda/conf/bpm-platform.xml
```

1. You copy the scripts folder (common/tasklist/scripts) into /camunda/webapps/camunda/app/tasklist/scripts
2. You copy the styles folder (common/tasklist/styles) into /camunda/webapps/camunda/app/tasklist/styles
3. you copy the forms folder (common/forms) into /camunda/webapps/forms/
4. you copy the jar into /camunda/lib/
5. you update your bpm-platform.xml file with the plugin line as indicated in https://github.com/StephenOTT/camunda-formio-plugin/blob/master/docker/bpm-platform.xml#L38-L40

**Comment by TEJAPS** [comment]
Thanks for quick response.
this jar formfieldvalidator-*-server-plugin.jar of step 4 , i am not able to find in the github directory.

**Comment by StephenOTT** [comment]
https://github.com/StephenOTT/camunda-formio-plugin/releases

**Comment by cybrpimp** [comment]
I too am trying to get the plugin installed on Tomcat Standalone.  I'll start from the top and report back any issues.

Thanks

**Comment by cybrpimp** [comment]
Ok, so do the files we overwrite the files in the scripts folder or create a new folder?

I already have an existing config.js file in here with settings so I'm not sure if we are to overwrite or put in a sub folder.

**Comment by StephenOTT** [comment]
Have you customized the config.js in your tomcat install?

**Comment by cybrpimp** [comment]
For the benefit of others here is what copied from your config.js and added to the camTasklistConfi tree;

Please note, I added a "Comma" at the end to separate the data elements.

` 
customScripts: {
        ngDeps: [],
        deps: ['loadFormio', 'loadformio'],
        paths: {
            'loadFormio': 'scripts/loadFormio',
            'loadformio': 'scripts/formio.full.min'
        }
    },
`
I'll continue testing using a form in a process and report back if issues.

Thanks

**Comment by StephenOTT** [comment]
@TEJAPS If you run Docker desktop, your configuration setup would be much less burdensome :)

**Comment by StephenOTT** [comment]
@cybrpimp If you run Docker desktop, your configuration setup would be much less burdensome :)

**Comment by StephenOTT** [comment]
Did you get is working?

**Comment by cybrpimp** [comment]
Yes sir, I was able to get it working.  Thanks!
