### ISSUE TITLE
Clarification on accessing the variables in forms

### ISSUE THREAD

**Issue by cybrpimp** [StephenOTT/camunda-formio-plugin#36]
Is there an example BPMN file showing how to setup the variables and access them once the form is submitted?

"Under the API tab of a component create a custom property with the following format:"

Also, can you clarify what program you are in when you made this instruction?

**Comment by StephenOTT** [comment]
https://github.com/StephenOTT/camunda-formio-plugin/tree/master/bpmn

See the MyUT1 json for the user task that is using the variable.

Variables in the Form are configured through the form builder.  When you edit a form component there is a "API" Tab.:
<img width="952" alt="formbuild1" src="https://user-images.githubusercontent.com/1994838/94685599-a72f3a80-02f7-11eb-8837-2d63bd6b5684.png">
