### ISSUE TITLE
Empty form

### ISSUE THREAD

**Issue by SouhailBS** [StephenOTT/camunda-formio-plugin#53]
when i start a new process the form is not getting rendered.
if i put something wrong an error message is displayed instead of the form but if everything is correct nothing would show up

**Comment by StephenOTT** [comment]
What is the message in the browser console?

**Comment by SouhailBS** [comment]
![image](https://user-images.githubusercontent.com/20427910/108834207-2e928880-75ce-11eb-8d48-16b58f2b3ea9.png)
![image](https://user-images.githubusercontent.com/20427910/108834260-436f1c00-75ce-11eb-9d93-692d59b3d660.png)

**Comment by StephenOTT** [comment]
Please try with a deployed form as part of the deployment.  You will need to deploy it along with your deployment and adjust your form key

**Comment by SouhailBS** [comment]
i deployed the bpmn sample from this repo along with all the json files but still nothing has changed.
in the browser network tab i can see that there is a request to fetch the json form fields and it did return the correct json componants.

**Comment by StephenOTT** [comment]
Can you create a sample BPMN with the configuration, your form, and details on which Camunda version you are using. And I can test from that.

**Comment by SouhailBS** [comment]
my camunda version: v7.13.0

[sample bpmn.zip](https://github.com/StephenOTT/camunda-formio-plugin/files/6034910/sample.bpmn.zip)

**Comment by StephenOTT** [comment]
Did you solve the issue?

**Comment by poiswe** [comment]
@StephenOTT Hi! I have the same problem, just set up a new project based on 7.16. I tried to update to the latest fomio-code but it's the same. I have deployed the json together with the bpmn. I can see the /resources and /data endpoints getting called to resolve the json...that seems to work, but rendering fails. NOTHING in the console. Any thoughts?

@StephenOTT after some research; "FormioUtils is not defined" ... so for some reason the utils are not intialized properly ?

Update; of course... after more digging i realized that nothing (not even Formio) was initialized .. at all ... and that lead me to realize that Camunda has changed (from v. 7.15) how the plugin system works. After some minor code changes formio now starts ...back to testing :)

**Comment by StephenOTT** [comment]
@poiswe great!  Could you share the code changes you made?
