### ISSUE TITLE
Comparison to the new Camunda Modeler form builder

### ISSUE THREAD

**Issue by CharlesIrvineKC** [StephenOTT/camunda-formio-plugin#62]
Off hand, this plugin and form.io seem to be an attractive alternative to the new Camunda Modeler forms capability. I wonder why this plugin wasn't adopted as the standard form builder feature rather than what was released. Any thoughts on this? Thanks

**Comment by StephenOTT** [comment]
Can only guess. But Camunda is building their cloud solution which is more and more proprietary so having the form builder under their design and build systems would be in their best interest.

**Comment by CharlesIrvineKC** [comment]
That crossed my mind as well.
